<a href="https://colab.research.google.com/github/deepasoman93/Python_ML_Basics/blob/main/GO_STP_7389_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment-4 | Numpy

1. Import the numpy package under the name np and Print the numpy version and the configuration 


In [ ]:
import numpy as np
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


2. Create a null vector of size 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create Simple 1-D array and check type and check data types in array

In [ ]:
a = np.arange(0, 100)
print('Type:', type(a))

Type: <class 'numpy.ndarray'>


In [ ]:
d= a.dtype
print('Datatype:', d)

Datatype: int64


4. How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
n = a.ndim
print('No of dimensions:', n)

No of dimensions: 1


In [ ]:
n= a.itemsize
print('No of bytes per element:',n)

No of bytes per element: 8


In [ ]:
b= a.nbytes
print('No of bytes:',b)

No of bytes: 800


5. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
n = np.zeros(10)
n[4] = 1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6. Create a vector with values ranging from 10 to 49

In [ ]:
 n= np.arange(10,50)
 print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Reverse a vector (first element becomes last)

In [ ]:
 n= np.arange(10,50)
 print(n[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
n = np.arange(0,9)
n.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
n = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(n)

(array([0, 1, 4]),)

10. Create a 3x3 identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11. Create a 3x3x3 array with random values

In [ ]:
np.random.random((3, 3, 3))

array([[[0.15873448, 0.90733898, 0.41364209],
        [0.54345932, 0.96432626, 0.05577944],
        [0.82302637, 0.17938999, 0.88599365]],

       [[0.02409823, 0.6873761 , 0.58732871],
        [0.0515272 , 0.40957105, 0.11749806],
        [0.94300938, 0.8404953 , 0.10650222]],

       [[0.02135567, 0.54650287, 0.93359022],
        [0.1384189 , 0.24286169, 0.36861263],
        [0.3601689 , 0.28913246, 0.13366836]]])

12. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
n= np.random.random((10, 10))
print(n)

[[0.59144039 0.76574995 0.95702931 0.86832294 0.41492867 0.03182671
  0.2481878  0.93823896 0.09860072 0.48118058]
 [0.82379671 0.30587583 0.78533739 0.62284336 0.91535863 0.52160141
  0.53344875 0.40774163 0.79113022 0.81646585]
 [0.70378102 0.91794374 0.17784645 0.52927881 0.60179624 0.24532862
  0.6196833  0.82705315 0.93333673 0.46343005]
 [0.2987396  0.28278244 0.16140525 0.15980997 0.11069974 0.80296426
  0.26761423 0.46476955 0.83587211 0.58085828]
 [0.40149138 0.19561798 0.40758049 0.40184589 0.1703265  0.18002907
  0.05997992 0.06857646 0.03219053 0.1723224 ]
 [0.19079784 0.8433248  0.71859946 0.99849942 0.92331516 0.47974272
  0.30585205 0.84874262 0.52765658 0.26555625]
 [0.44230326 0.91583184 0.15660214 0.99941363 0.04240115 0.45791572
  0.31009355 0.78206403 0.27197703 0.8593316 ]
 [0.5430464  0.77054286 0.28494131 0.98518663 0.75644347 0.77644483
  0.39569939 0.91957348 0.58429087 0.32791603]
 [0.83271143 0.30064605 0.17053965 0.33169449 0.97283361 0.24761566
  0.27794523

In [ ]:
np.min(n)

0.0318267065823965

In [ ]:
np.max(n)

0.9994136331808287

13. Create a random vector of size 30 and find the mean value

In [ ]:
n= np.random.random((30))
print(n)

[0.7260618  0.53228978 0.87336807 0.56341106 0.57416087 0.73801614
 0.56290344 0.43071625 0.82056354 0.11301657 0.25026614 0.75088122
 0.46240524 0.64580963 0.94134469 0.33366688 0.11144422 0.98181917
 0.65770797 0.37639624 0.99533804 0.20125173 0.3513629  0.68733322
 0.25776175 0.52379868 0.34061976 0.1339807  0.294304   0.12477793]


In [ ]:
np.mean(n)

0.5118925874649483

14. Create a 2d array with 1 on the border and 0 inside

In [ ]:
n = np.ones((10,10))
n[1:9, 1:9] = 0
print(n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [ ]:
n = np.ones((10,10))
print('Before', n)

n[:1, :] = 0
n[:, :1] = 0
n[9:, :] = 0
n[:, 9:] = 0
print('After', n)

Before [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
After [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
i = np.arange(1,15).reshape(2,7)
print(i)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
i[1,5]

13

In [ ]:
i[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
i[:,2]

array([ 3, 10])

In [ ]:
i[0,1::2]

array([2, 4, 6])

In [ ]:
i[1,5] = 20
print(i)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


17. How to Convert a 1D array to a 2D array with 2 rows

In [ ]:
n = np.arange(0,8)
n

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
n.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:
a = np.array([1,2,3])`

Desired Output:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1, 2, 3])
np.append(np.repeat(a,3), np.tile(a,3))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19. Write a program to show how Numpy taking less memory compared to Python List?

In [ ]:
import sys
n= [0,1,2,3,4,5,6,7,8]
sys.getsizeof(n) * len(n)

1296

In [ ]:
a = np.arange(9)
a.size * a.itemsize

72

20. Write a program to show how Numpy taking less time compared to Python List?

In [ ]:
S= range(10)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
D= np.arange(10)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  480
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  80
